// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Kiki.CourierService.Shared.Models
{
    public partial class KikicourierserviceContext : DbContext
    {
        public KikicourierserviceContext()
        {
        }

        public KikicourierserviceContext(DbContextOptions<KikicourierserviceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Offer> Offer { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Offer>(entity =>
            {
                entity.Property(e => e.DiscountRate).HasColumnType("decimal(3, 2)");

                entity.Property(e => e.DistanceRangeFrom).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.DistanceRangeTo).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.OfferCode)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.WeightRangeFrom).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.WeightRangeTo).HasColumnType("decimal(5, 2)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}