// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Kiki.CourierService.Shared.Models
{
    public partial class Offer
    {
        public int Id { get; set; }
        public string OfferCode { get; set; }
        public double DiscountRate { get; set; }
        public bool? IsActive { get; set; }
        public double DistanceRangeFrom { get; set; }
        public double DistanceRangeTo { get; set; }
        public double WeightRangeFrom { get; set; }
        public double WeightRangeTo { get; set; }
    }
}